hacktivistcamp18/urls.py
from django.contrib import admin
from django.urls import path
from .views import find_participant

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",find_participant)
]

hacktivistcamp18/models.py
from django.db import models

class Registration(models.Model):
    glugs = (
            ("AITCM","AIT-ChickMagluru"),
            ("GLUE","GLUE GEC Hassan"),
            ("GEON","GEON GEC Hassan"),
            ("Hassan","Hassan"),
            ("RIT","RIT Hassan"),
            ("BIT","BIT Mangalore"),
            ("PESCE-Mandya","PESCE Mandya"),
            ("Oxford","Oxford Bangalore"),
            ("SJBIT","SJBIT Bangalore"),
            ("SVIT","SVIT Bangalore"),
            ("VCET","VCET Mangalore"),
            ("FSMK","FSMK"),
            ("FSMK Community Center","FSMK Community Center")
            )
    participant_type = (
                ("participant","Participant"),
                ("volunteer","Volunteer"),
                ("speaker","Speaker")
            )
    payment_status = (
                ("To Pay","To be Paid"),
                ("Paid to co-ordinator","Paid to Co-ordinator"),
                ("Individual","Directly transferred to bank"),
                ("Camp","Will pay in camp"),
                ("unknown","Status Unknown. Call Participant")
            )

    gender = (
            ("male","Male"),
            ("female","Female"),
            ("others","Others")
            )
    arriving_status = (
                ("WA","Wednesday Afternoon ( 1 - 3 PM)"),
                ("WE","Wednesday Evening (3 - 5 PM)"),
                ("TM","Thursday Morning (4 -6:15AM)"),
                ("FM","Friday Morning"),
                ("SA","Saturday")
            )
    name = models.CharField(max_length=200)
    contact = models.PositiveIntegerField()
    email = models.EmailField()
    glug = models.CharField(max_length=100,choices=glugs)
    gender = models.CharField(max_length=30,choices=gender)
    semester = models.PositiveIntegerField()
    responsibility = models.TextField(blank=True, null=True)
    participant_type = models.CharField(max_length=100,choices=participant_type)
    payment_status = models.CharField(max_length=100,choices=payment_status)
    comments = models.TextField(blank=True,null=True)
    arriving_status = models.CharField(max_length=50,choices = arriving_status)

hacktivistcamp18/views.py
from django.shortcuts import render
from .models import Registration

def find_participant(request):
    if request.method == "POST":
        contact = request.POST.get("mobile_number")
        if contact:
            participant = Registration.objects.filter(contact=contact).first()
            if participant:
                return render(request,"find_participant.html",{"participant":participant})
            else:
                return render(request,"find_participant.html",{"error":"Participant not found"})

    return render(request,"find_participant.html",{})

templates/find_participant.html
<style>
html, body{
  width: 100vw;
  height:100vh;
}
input{
    height:50px;
    width:350px;
    font-size:14pt;
}
  </style>

<h3> Enter your mobile number to check your registration status for FSMK Hacktivist Camp 2018</h3>
<form action="." method="POST">
  <input type="number" placeholder="Enter your mobile number" name="mobile_number">
  {%csrf_token%}
  <button type="submit"> Am I registered </button>
</form>

{% if participant %}
<table>
  <tbody>
    <tr>
      <td>Participant Name</td> <td>{{participant.name}} </td>
    </tr>
    <tr>
      <td> GLUG </td> <td> {{participant.get_glug_display}}</td>
    </tr>
    <tr>
      <td> Payment Status </td>
      <td> {{participant.get_payment_status_display}} </td>
    </tr> 
    <tr>
      <td> Arriving When </td>
      <td> {{participant.get_arriving_status_display}}</td>
    </tr>
    </tbody>
    </table>
{% endif %}
{%if error %}
  <h3> You dont seem to have registered . Please contact your co-ordinator to get you registered </h3>
  {% endif %}